#!/usr/bin/env bash
set -euo pipefail

# If repo root is current working dir:
python -m pip install -e .


python run.py \
  --swc-dir "${SWC_DIR:-/data/swc_refinement/final-world}" \
  --transform-dir "${1:-${TRANSFORM_DIR:-}}" \
  --manual-df-path "${2:-${MANUAL_DF_PATH:-}}" \
  --output-root "${OUTPUT_ROOT:-/results/exaspim_swc_transform}" \
  --metadata-dir "${METADATA_DIR:-/results/exaspim_swc_transform}" \
  --naming-style "${NAMING_STYLE:-preserve}"
