# hash:sha256:91f839cfd71c36413e37d912f36a591017edf610ce743e686d587825dd4120cd
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/cuda-miniconda-jupyterlab:latest

ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_ASKPASS
COPY git-askpass /
